furima/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('', include('shop.urls')),# 2. 自作の機能へ振り分け
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')), # 1. 元々提供されている機能へ振り分け
]

shop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views

app_name = 'shop'
urlpatterns = [
    # トップページ(商品一覧)
    path('', views.ViewItemList.as_view(), name='top'),

    # 
    # 商品情報
    # 
    # 商品情報登録
    path('sell/', views.ViewCreateItem, name='createItem'),
    # 商品情報詳細
    path('item/<uuid:id>', views.ViewReadItem, name='readItem'),
    # 商品情報変更
    path('updateItem/<slug:id>', views.ViewUpdateItem, name='updateItem'),
    path('updateItemComplete/<slug:id>', views.ViewUpdateItemComplete, name='updateItemComplete'),
    # 商品情報削除
    path('deleteItem/<slug:id>', views.ViewDeleteItem, name='deleteItem'),

    # 
    # 利用者情報
    # 
    # 利用者情報登録
    path('signup/', views.SignUpView.as_view(), name='createUser'),
    # 利用者情報詳細
    path('user/<int:id>', views.ViewReadUser, name='readUser'),
    # 利用者情報変更
    path('editUser', views.ViewUpdateUser, name='updateUser'),
    path('updateUser', views.ViewUpdateUserComplete, name='updateUserComplete'),
    # 利用者情報削除(退会)
    path('deleteUserConfirm', TemplateView.as_view(template_name='shop/TempDeleteUserConfirm.html'), name='deleteUserConfirm'),
    path('deleteUserComplete', views.DeleteView.as_view(), name='deleteUserComplete'),

    # 
    # ログイン / ログアウト / マイページ
    # 
    # ログイン
    path('login/', views.LoginView.as_view(), name='login'),
    # ログアウト
    path('logout/', views.Logout.as_view(), name='logout'),
    # マイページ
    path('mypage/', views.ProfileView.as_view(), name='mypage'),

    # 
    # パスワード
    # 
    # パスワード変更
    path('passwordChange/', views.PasswordChange.as_view(), name='passwordChange'),
    path('passwordChangeDone/', views.PasswordChangeDone.as_view(), name='passwordChangeDone'),

    # パスワードリセット
    path('passwordResetForm/', views.passwordResetForm.as_view(), name='passwordResetForm'),
    path('passwordResetDone/', views.passwordResetDone.as_view(), name='passwordResetDone'),
    path('passwordResetEmail/', views.passwordResetEmail.as_view(), name='passwordResetEmail'),
    path('passwordResetConfirm/<uidb64>/<token>/', views.passwordResetConfirm.as_view(), name='passwordResetConfirm'),
    path('passwordResetComplete/', views.passwordResetComplete.as_view(), name='passwordResetComplete'),

    # 
    # 商品取引
    # 
    # 商品購入
    path('purchase/<uuid:id>', views.ViewPurchase, name='purchase'),
    path('purchaseComplete/<uuid:id>', views.ViewPurchaseComplete, name='purchaseComplete'),
    # 取引
    path('transaction/<uuid:id>', views.ViewTransaction, name='transaction'),
    path('transactionShipped/<uuid:id>', views.ViewTransactionShipped, name='transactionShipped'),
    path('transactionArrived/<uuid:id>', views.ViewTransactionArrived, name='transactionArrived'),
    
    # 
    # 一覧
    # 
    # いいね一覧
    path('favorite/', views.ViewListFavorite.as_view(), name='favoriteList'),
    # 出品一覧
    path('sellList/', views.ViewListSell.as_view(), name='sellList'),
    # 購入一覧
    path('buyList/', views.ViewListBuy.as_view(), name='buyList'),
]
if settings.DEBUG:
    urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

shop/views.py
from datetime import datetime
from urllib import request, response
from numpy import var
from .models import (
    ModelItemList,
    ModelListStatus,
    ModelShipStatus,
    ModelTransactionStatus
)
from .form import (
    userCreateForm,
    userUpdateForm,
    itemForm,
    passwordChangeForm,
    passwordResetForm,
)
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import(
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView
)
from django.contrib.auth import (
     get_user_model,
     login as auth_login,
     logout as auth_logout
)
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from django.views.generic import ListView
from django.db.models import Q
from django.core.paginator import(
    Paginator,
    EmptyPage,
    PageNotAnInteger
)

User = get_user_model()
# 
# トップページ
# 
class ViewItemList(ListView):
    """トップページ"""
    model = ModelItemList
    template_name = 'shop/TempTop.html'
    paginate_by = 9

    # 一覧表示、検索機能
    def get_queryset(self):
        q_word = self.request.GET.get('query')
        if q_word:
            object_list = ModelItemList.objects.filter(
                Q(name__icontains=q_word)).order_by('-lastUpdate')
        else:
            object_list = ModelItemList.objects.all().order_by('-lastUpdate')
        return object_list

# 
# 商品情報
# 
def ViewCreateItem(request):
    """商品情報登録"""
    if request.method == 'POST':
        varForm = itemForm(request.POST or None,request.FILES)
        if varForm.is_valid():
            list = ModelItemList()
            list.image1 = varForm.cleaned_data['image1']
            list.name = varForm.cleaned_data['name']
            list.price = varForm.cleaned_data['price']
            list.category = varForm.cleaned_data['category']
            list.status = varForm.cleaned_data['status']
            list.description = varForm.cleaned_data['description']
            list.bearShippingFee = varForm.cleaned_data['bearShippingFee']
            list.shippingFee = varForm.cleaned_data['shippingFee']
            list.shippingMethod = varForm.cleaned_data['shippingMethod']
            list.shipArea = varForm.cleaned_data['shipArea']
            list.shippingTime = varForm.cleaned_data['shippingTime']

            ModelItemList.objects.create(
                # id = list.id,
                image1 = list.image1,
                name = list.name,
                price = list.price,
                category = list.category,
                status = list.status,
                description = list.description,
                bearShippingFee = list.bearShippingFee,
                shippingFee = list.shippingFee,
                shippingMethod = list.shippingMethod,
                shipArea = list.shipArea,
                shippingTime = list.shippingTime,
                seller = request.user,
                sellDate = datetime.now(),
                lastUpdate = datetime.now()
            )
            messages.success(request, '商品を出品しました。')
            return redirect('shop:top')
    else:
        varForm = itemForm()
        context = {
            'form': varForm
        }
    return render(request, 'shop/TempCreateItem.html', context)
    
def ViewReadItem(request, id):
    """商品情報詳細"""
    varItem = get_object_or_404(ModelItemList, pk=id)
    context = {
        'item': varItem
    }
    return render(request,
                  'shop/TempReadItem.html', context)

def ViewUpdateItem(request, id):
    """商品情報編集"""
    varItem = get_object_or_404(ModelItemList, pk=id)
    varForm = itemForm(instance=varItem)
    context = {
        'item':varItem,
        'form':varForm,
    }
    return render(request, 'shop/TempUpdateItem.html', context)

def ViewUpdateItemComplete(request,id):
    """商品情報編集 完了"""
    if request.method == 'POST':
        varItem = get_object_or_404(ModelItemList,pk=id)
        varForm = itemForm(request.POST,instance=varItem)
        if varForm.is_valid():
            varForm.save()
    messages.success(request, '商品情報を更新しました。')
    return redirect('shop:readItem', id=id)

def ViewDeleteItem(request,id):
    """商品情報削除"""
    varItem = get_object_or_404(ModelItemList,pk=id)
    varItem.delete()
    messages.warning(request, '商品情報を削除しました。')
    return redirect('shop:top')

# 
# 利用者情報
# 
class SignUpView(generic.CreateView):
    """利用者情報登録"""
    form_class = userCreateForm
    success_url = reverse_lazy('login')
    template_name = 'shop/TempCreateUser.html'
    def form_valid(self, form):
        user = form.save() # formの情報を保存
        auth_login(self.request, user) # 認証
        self.object = user
        messages.success(self.request, 'ユーザー登録が完了しました。ようこそ')
        return redirect('shop:top')

def ViewReadUser(request,id):
    """利用者情報詳細"""
    varUser = get_object_or_404(User, pk=id)
    verItem = ModelItemList.objects.filter(seller=id).order_by('-id')
    context = {
        'user': varUser,
        'item': verItem,
    }
    return render(request, 'shop/TempReadUser.html', context) 

def ViewUpdateUser(request):
    """利用者情報更新"""
    varUser = get_object_or_404(User, pk=request.user.id)
    verForm = userUpdateForm(instance=varUser)

    context = {
        'user':varUser,
        'form':verForm,
    }
    return render(request, 'shop/TempUpdateUser.html', context)

def ViewUpdateUserComplete(request):
    """利用者情報更新 完了"""
    if request.method == 'POST':
        varUser = get_object_or_404(User,pk=request.user.id)
        varForm = userUpdateForm(request.POST,instance=varUser)
        varForm.save()
        messages.success(request, 'ユーザ情報を更新しました。')
    return redirect('shop:mypage')

class DeleteView(LoginRequiredMixin, generic.View):
    """利用者情報削除"""
    def get(self, *args, **kwargs):
        varUser = User.objects.get(email=self.request.user.email)
        varUser.is_active = False
        varUser.save()
        auth_logout(self.request)
        messages.warning(self.request, '退会しました。ご利用いただきありがとうございました。')
        return redirect('shop:top')

# 
# ログイン / ログアウト / マイページ
# 
class Logout(LoginRequiredMixin, LogoutView):
    """ログアウト"""
    template_name = 'shop/TempLogout.html'

class ProfileView(LoginRequiredMixin, generic.View):
    """マイページ"""
    def get(self, *args, **kwargs):
        return render(self.request,'shop/TempMypage.html')

# 
# パスワード
# 
class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = passwordChangeForm
    success_url = reverse_lazy('shop:passwordChangeDone')
    template_name = 'shop/TempPasswordChange.html'

class PasswordChangeDone(PasswordChangeDoneView):
    """パスワード変更しました"""
    template_name = 'shop/TempPasswordChangeDone.html'

# 1.パスワードリセットページでメールアドレスを入力
class passwordResetForm(PasswordResetView):
    """パスワードリセットフォーム"""
    form_class = passwordResetForm
    template_name = 'shop/TempPasswordResetForm.html'
    from_email = 'yuki700g@gmail.com'
    success_url = reverse_lazy('shop:passwordResetDone')

# 2.メール送信完了ページが表示され、パスワードリセットメールを受信
class passwordResetDone(PasswordResetDoneView):
    """パスワードリセット メール送信完了"""
    template_name = 'shop/TempPasswordResetDone.html'

# 3.メールに記載されているリンクをクリック
class passwordResetEmail(PasswordResetView):
    """パスワードリセットEメール"""
    email_template_name = 'shop/TempPasswordResetEmail.html'
    template_name = 'shop/TempPasswordResetEmail.html'
    from_email = 'yuki700g@gmail.com'
    success_url = reverse_lazy('shop:TempPasswordResetDone')


# 4.パスワード更新ページから新パスワードを設定
class passwordResetConfirm(PasswordResetConfirmView):
    """パスワードリセット確認"""
    template_name = 'shop/TempPasswordResetConfirm.html'

# 5.パスワード更新完了ページが表示
class passwordResetComplete(PasswordResetCompleteView):
    """パスワードリセット完了"""
    template_name = 'shop/TempPasswordResetComplete.html'

# 
# 商品取引
# 
def ViewPurchase(request, id):
    """商品購入"""
    varItem = get_object_or_404(ModelItemList, pk=id)
    context = {
        'item': varItem
    }
    return render(request,
                  'shop/TempPurchase.html', context)

def ViewPurchaseComplete(request, id):
    """商品購入処理"""
    # レコード作成・更新用のモデルクラスインスタンスを作成
    varItem = ModelItemList.objects.get(pk = id)
    varSeller = varItem.seller
    varTransactionStatusStartTransaction = ModelTransactionStatus.objects.get(id = 1)
    varShipStatusUnsent = ModelShipStatus.objects.get(id = 0)
    varListStatusUnselling = ModelListStatus.objects.get(id = 1)

    # 商品レコードを更新
    varItem.lastUpdate = datetime.now()
    varItem.buyer = request.user
    varItem.seller = varSeller
    varItem.listStatus = varListStatusUnselling
    varItem.transactionStatus = varTransactionStatusStartTransaction
    varItem.shipStatus = varShipStatusUnsent
    varItem.transactionStartDate = datetime.now()
    varItem.save()

    messages.success(request, '商品を購入しました。')
    return redirect('shop:readItem', id = varItem.id)

def ViewTransaction(request, id):
    """取引"""
    varItem = get_object_or_404(ModelItemList, pk=id)
    context = {
        'item':varItem,
    }
    return render(request, 'shop/TempTransaction.html', context)

def ViewTransactionShipped(request,id):
    """取引 発送済み"""
    varTransactionStatusShipped = ModelTransactionStatus.objects.get(id=2)
    varShipStatusShipping = ModelShipStatus.objects.get(id=2)

    # 商品レコードを更新
    varItem = ModelItemList.objects.get(pk=id)
    varItem.transactionStatus = varTransactionStatusShipped
    varItem.shipStatus = varShipStatusShipping
    varItem.lastUpdate = datetime.now()
    varItem.save()

    messages.success(request, '発送連絡をしました。')
    return redirect('shop:transaction', id)

def ViewTransactionArrived(request,id):
    """取引 受け取り完了"""
    varTransactionComplete = ModelTransactionStatus.objects.get(id=3)

shop/templates/shop/TempDeleteUserConfirm.html
{% extends "shop/base.html" %}
{% block title %}フリマサイト | アカウント削除{% endblock title %}
{% load bootstrap4 %}
{% block content %}
    <p>アカウントを削除します。よろしいですか?</p>
    <a class="btn btn-success btn-block" href="{% url 'shop:top' %}">やっぱりやめる</a>
    <a class="btn btn-danger btn-block" href="{% url 'shop:deleteUserComplete' %}">アカウントを削除する</a>
{% endblock %}

shop/templates/shop/TempListSell.html
{% extends "shop/base.html" %}
{% block title %}フリマサイト | 出品リスト{% endblock title %}
{% load bootstrap4 %}
{% block content %}

<h5 class="text-center">出品リスト</h5>
<table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>画像</th>
        <th>商品名</th>
        <th>金額</th>
        <th>状態</th>        
        <th>編集</th>
      </tr>
    </thead>
    <tbody>
        {% for item in object_list %}
        <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>
            <a href="{% url 'shop:readItem' id=item.id%}">
                <img src="/{{ item.image1 }}"
                data-toggle="tooltip"
                title="{{ item.name }}"
                width="100px">
            </a>
        </td>
        <td>{{ item.name }}</td>
        <td>{{ item.price }} 円</td>
        <td>{{ item.transactionStatus }}</td>
        <!-- 出品状態でない商品は商品情報の編集不可 -->
        {% if item.transactionStatus.id == 0 %}
            <td><a href="{% url 'shop:updateItem' id=item.id %}" class="btn btn-outline-warning">編集</a></td>
        {% else %}
            <td><button type="button" class="btn btn-outline-warning" disabled>編集</button></td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

shop/templates/shop/TempLogin.html
{% extends "shop/base.html" %}
{% block title %}フリマサイト | ログイン{% endblock title %}
{% load bootstrap4 %}
{% block content %}
<form action="{% url 'login' %}" method="POST">
    {% bootstrap_form form %}
        <button type="submit" class="btn btn-success btn-block">ログイン</button>
        <input type="hidden" name="next" value="{{ next }}"/>
        {% csrf_token %}
</form>
<a href="{% url 'shop:top' %}" method="post" class="btn btn-secondary btn-block">トップページ</a>
<a href="{% url 'shop:passwordResetForm' %}">パスワードをお忘れですか?</a>
{% endblock %}

shop/templates/shop/TempMypage.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}
{% block title %}フリマサイト | マイページ{% endblock title %}
{% block content %}
<!-- 利用者情報変更ドロップダウンメニュー -->
<div class="dropdown">
    <button class="btn bg-secondary text-white dropdown-toggle"
            type="button" id="dropdownMenu1" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
        ユーザ情報修正
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <a class="dropdown-item" href="{% url 'shop:updateUser' %}">プロフィールの編集</a>
        <a class="dropdown-item" href="{% url 'shop:passwordChange' %}">パスワードの変更</a>
        <a class="dropdown-item" href="{% url 'shop:deleteUserConfirm' %}">退会</a>
    </div>
</div>

<a href="{% url 'shop:favoriteList' %}" class="btn btn-outline-dribble btn-block">いいね一覧(未実装)</a>
<a href="{% url 'shop:sellList' %}" class="btn btn-outline-success btn-block">出品した商品</a>
<a href="{% url 'shop:buyList' %}" class="btn btn-outline-warning btn-block">購入した商品</a>

<!-- 利用者情報表示部分 -->
<div class="d-flex align-items-center justify-content-center">
    <img src="/{{ user.picture }}"
    class="img-thumbnail rounded d-block mx-auto"
    alt="{{ user.name }}"
    width="200px"
    height="200px"
    data-toggle="tooltip"
    title="{{ user.name }}">
</div>

<table class="table borderless">
    <tbody>
        <tr>
            <th scope="row">ユーザ名</th>
            <td>{{ user.name }}</td>
        </tr>
        <tr>
            <th scope="row">自己紹介</th>
            <td>{{ user.description }}</td>
        </tr>
        <tr>
            <th scope="row">E-mail</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th scope="row">登録日</th>
            <td>{{ user.date_joined|date:"Y/m/d" }}</td>
        </tr>
    </tbody>
</table>
{% endblock %}

shop/templates/shop/TempPurchase.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}
{% block title %}購入{% endblock title %}
{% block content %}

<h5 class="text-center">以下の商品を購入します。</h5>
<h5 class="text-center">よろしいですか？</h5>

{% if item.image1 %}
<div class="d-flex align-items-center justify-content-center">
    <img src="/{{ item.image1 }}" class="img-thumbnail">
</div>
{% endif %}
<table class="table">
    <tbody>
        <tr>
            <td>カテゴリー</td>
            <td>{{ item.category }}</td>
        </tr>
        <tr>
            <td>商品の状態</td>
            <td>{{ item.status }}</td>
        </tr>
        <tr>
            <td>配送料</td>
            <td>{{ item.shippingFee }}円</td>
        </tr>
        <tr>
            <td>配送料の負担</td>
            <td>{{ item.bearShippingFee }}</td>
        </tr>
        <tr>
            <td>発送方法</td>
            <td>{{ item.shippingMethod }}</td>
        </tr>
        <tr>
            <td>配送元の地域</td>
            <td>{{ item.shipArea }}</td>
        </tr>
        <tr>
            <td>発送までの日数</td>
            <td>{{ item.shippingTime }}</td>
        </tr>
        <tr>
            <td>出品者</td>
            <td>
                <a href="{% url 'shop:readUser' id=item.seller.id %}">{{ item.seller.name }}</a>
            </td>
        </tr>
    </tbody>
</table>
<h4 class="text-left">{{ item.name }}</h4>
<h4 class="text-danger text-right">{{ item.price }}円</h4>

<form action="{% url 'shop:purchaseComplete' id=item.id %}" method='post' class='form'>
    {% csrf_token %}
    <button type='submit' class='btn btn-danger btn-block'>購入</button>
    <a href='#' onclick="history.back(); return false;" class='btn btn-secondary btn-block'>戻る</a>
</form>
{% endblock content %}

shop/templates/shop/TempReadItem.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}
{% block title %}{{ item.name }} | フリマサイト{% endblock title %}
{% block content %}
<!-- 「販売中でない」かつ、ログイン中の利用者が購入者、販売者でない場合、メッセージ表示 -->
{% if item.listStatus.id == 1 and user != item.buyer and user != item.seller %}
    <div class="alert alert-danger text-center" role="alert">
        <strong>SOLD OUT</strong> この商品は売り切れています。
    </div>
{% endif %}
<!-- 取引情報が存在しない場合 -->
{% if item.transactionStatus.id != 0 %}
    <!-- ログイン中の利用者が購入者の場合、メッセージ表示、取引画面遷移ボタン表示 -->
    {% if user == item.buyer %}
    <div class="alert alert-success text-center" role="alert">
        <strong>gratz!</strong> 商品を購入しました。
    </div>
    <a href="{% url 'shop:transaction' id=item.id %}" class="btn btn-warning btn-block">取引画面へ</a>
    {% endif %}
    <!-- ログイン中の利用者が販売者の場合、メッセージ表示、取引画面遷移ボタン表示 -->
    {% if user == item.seller %}
    <div class="alert alert-success text-center" role="alert">
        <strong>gratz!</strong> あなたの商品が購入されました。
    </div>
    <a href="{% url 'shop:transaction' id=item.id %}" class="btn btn-warning btn-block">取引画面へ</a>
    {% endif %}
{% endif %}

<!-- 商品画像カルーセル表示 -->
{% if item.image1 %}
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleControls" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleControls" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="/{{ item.image1 }}" class="d-block w-100" alt="{{ item.name }}">
            </div>
            {% if item.image2 %}
                <div class="carousel-item">
                    <img src="/{{ item.image2 }}" class="d-block w-100" alt="{{ item.name }}">
                </div>
            {% endif %}
            {% if item.image3 %}
                <div class="carousel-item">
                    <img src="/{{ item.image3 }}" class="d-block w-100" alt="{{ item.name }}">
                </div>
            {% endif %}
            {% if item.image4 %}
                <div class="carousel-item">
                    <img src="/{{ item.image4 }}" class="d-block w-100" alt="{{ item.name }}">
                </div>
            {% endif %}
            {% if item.image5 %}
                <div class="carousel-item">
                    <img src="/{{ item.image5 }}" class="d-block w-100" alt="{{ item.name }}">
                </div>
            {% endif %}
            {% if item.image6 %}
                <div class="carousel-item">
                    <img src="/{{ item.image6 }}" class="d-block w-100" alt="{{ item.name }}">
                </div>
            {% endif %}
            {% if item.image7 %}
                <div class="carousel-item">
                    <img src="/{{ item.image7 }}" class="d-block w-100" alt="{{ item.name }}">
                </div>
            {% endif %}
            {% if item.image8 %}
                <div class="carousel-item">
                    <img src="/{{ item.image8 }}" class="d-block w-100" alt="{{ item.name }}">
                </div>
            {% endif %}
            {% if item.image9 %}
                <div class="carousel-item">
                    <img src="/{{ item.image9 }}" class="d-block w-100" alt="{{ item.name }}">
                </div>
            {% endif %}
            {% if item.image10 %}
                <div class="carousel-item">
                    <img src="/{{ item.image10 }}" class="d-block w-100" alt="{{ item.name }}">
                </div>
            {% endif %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">前へ</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">次へ</span>
        </a>
    </div>
{% endif %}
<h4 class="text-left">{{ item.name }}</h4>
<h4 class="text-danger text-right">{{ item.price }}円</h4>
<table class="table">
    <tbody>
        <tr>
            <td>カテゴリー</td>
            <td>{{ item.category }}</td>
        </tr>
        <tr>
            <td>商品の状態</td>
            <td>{{ item.status }}</td>
        </tr>
        <tr>
            <td>配送料</td>
            <td>{{ item.shippingFee }}円</td>
        </tr>
        <tr>
            <td>配送料の負担</td>
            <td>{{ item.bearShippingFee }}</td>
        </tr>
        <tr>
            <td>発送方法</td>
            <td>{{ item.shippingMethod }}</td>
        </tr>
        <tr>
            <td>配送元の地域</td>
            <td>{{ item.shipArea }}</td>
        </tr>
        <tr>
            <td>発送までの日数</td>
            <td>{{ item.shippingTime }}</td>
        </tr>
        <tr>
            <td>出品者</td>
            <td>
                <a href="{% url 'shop:readUser' id=item.seller.id %}">{{ item.seller.name }}</a>
            </td>
        </tr>
    </tbody>
</table>
<p class="text-right">最終更新日 : {{ item.lastUpdate|date:"Y/m/d" }}</p>
<!-- 商品の出品者ID==商品の出品者IDである場合、購入ボタンを表示しない -->
<!-- 商品の出品者ID==ログインユーザのIDであれば商品編集ボタンを表示する -->
{% if user.is_authenticated and item.seller.id == user.id %}
        <!-- 出品状態でない商品は商品情報の編集不可 -->
        {% if item.transactionStatus.id == 0 %}
            <a href="{% url 'shop:updateItem' id=item.id %}" class="btn btn-secondary btn-block">商品を編集</a>
        {% else %}
            <button type="button" class="btn btn-secondary btn-block" disabled>商品は購入されたため、商品方法は変更できません。</button>
        {% endif %}
    {% else %}
    <!-- 出品状態がLISTINGでない場合、購入できないボタンを表示する -->
    {% if item.listStatus.id == 0 %}
        <a href="{% url 'shop:purchase' id=item.id %}" class="btn btn-success btn-block">購入</a>
    {% else %}
        <button type="button" class="btn btn-secondary btn-block" disabled>購入できません</button>
    {% endif %}
{% endif %}
{% endblock content %}

shop/templates/shop/TempUpdateItem.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}
{% block title %}フリマサイト | 商品情報編集{% endblock title %}
{% block content %}



<a class="btn btn-danger btn-block" href="{% url "shop:deleteItem" id=item.id%}" role="button">商品を削除する</a>



<form action='{% url "shop:updateItemComplete" id=item.id%}' method='post' class='form'>
    {% csrf_token %}
    {% bootstrap_form form  %}
    <button type='submit' class='btn btn-success btn-block'>更新</button>
</form>
<a href='#' onclick="history.back(); return false;" class='btn btn-secondary btn-block'>戻る</a>
{% endblock content %}